version: 2
jobs:
 
 lint:
  macos:
   xcode: "10.3.0"
  steps:
   - checkout
   - run:
     name: Install Swiftlint
     command: ./Scripts/install_swiftlint.sh
   - run:
     name: Lint
     command: swiftlint
   
  build-and-test:
    macos:
      xcode: "10.3.0"
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: SunLight

      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output

workflows:
  version: 2
  build-test-lint:
    jobs:
      - lint
      - build-and-test
